// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use std::fmt;
use std::mem;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "HitakiEfwProtocol")]
    pub struct EfwProtocol(Interface<ffi::HitakiEfwProtocol, ffi::HitakiEfwProtocolInterface>);

    match fn {
        type_ => || ffi::hitaki_efw_protocol_get_type(),
    }
}

impl EfwProtocol {
    pub const NONE: Option<&'static EfwProtocol> = None;
}

pub trait EfwProtocolExt: 'static {
    #[doc(alias = "hitaki_efw_protocol_receive_response")]
    fn receive_response(&self, buffer: &[u8]);

    #[doc(alias = "hitaki_efw_protocol_transmit_request")]
    fn transmit_request(
        &self,
        category: u32,
        command: u32,
        args: &[u32],
    ) -> Result<u32, glib::Error>;
}

impl<O: IsA<EfwProtocol>> EfwProtocolExt for O {
    fn receive_response(&self, buffer: &[u8]) {
        let length = buffer.len() as usize;
        unsafe {
            ffi::hitaki_efw_protocol_receive_response(
                self.as_ref().to_glib_none().0,
                buffer.to_glib_none().0,
                length,
            );
        }
    }

    fn transmit_request(
        &self,
        category: u32,
        command: u32,
        args: &[u32],
    ) -> Result<u32, glib::Error> {
        let arg_count = args.len() as usize;
        unsafe {
            let mut resp_seqnum = mem::MaybeUninit::uninit();
            let mut error = ptr::null_mut();
            let is_ok = ffi::hitaki_efw_protocol_transmit_request(
                self.as_ref().to_glib_none().0,
                category,
                command,
                args.to_glib_none().0,
                arg_count,
                resp_seqnum.as_mut_ptr(),
                &mut error,
            );
            let resp_seqnum = resp_seqnum.assume_init();
            assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(resp_seqnum)
            } else {
                Err(from_glib_full(error))
            }
        }
    }
}

impl fmt::Display for EfwProtocol {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("EfwProtocol")
    }
}
