// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod alsa_firewire;
pub use self::alsa_firewire::AlsaFirewireExt;
pub use self::alsa_firewire::{AlsaFirewire, NONE_ALSA_FIREWIRE};

mod efw_protocol;
pub use self::efw_protocol::EfwProtocolExt;
pub use self::efw_protocol::{EfwProtocol, NONE_EFW_PROTOCOL};

mod motu_command_dsp;
pub use self::motu_command_dsp::MotuCommandDspExt;
pub use self::motu_command_dsp::{MotuCommandDsp, NONE_MOTU_COMMAND_DSP};

mod motu_register_dsp;
pub use self::motu_register_dsp::MotuRegisterDspExt;
pub use self::motu_register_dsp::{MotuRegisterDsp, NONE_MOTU_REGISTER_DSP};

mod quadlet_notification;
pub use self::quadlet_notification::QuadletNotificationExt;
pub use self::quadlet_notification::{QuadletNotification, NONE_QUADLET_NOTIFICATION};

mod snd_dice;
pub use self::snd_dice::{SndDice, SndDiceClass, NONE_SND_DICE};

mod snd_digi00x;
pub use self::snd_digi00x::{SndDigi00x, SndDigi00xClass, NONE_SND_DIGI00X};

mod snd_efw;
pub use self::snd_efw::{SndEfw, SndEfwClass, NONE_SND_EFW};

mod snd_motu;
pub use self::snd_motu::{SndMotu, SndMotuClass, NONE_SND_MOTU};

mod snd_tascam;
pub use self::snd_tascam::{SndTascam, SndTascamClass, NONE_SND_TASCAM};

mod snd_unit;
pub use self::snd_unit::{SndUnit, SndUnitClass, NONE_SND_UNIT};

mod tascam_protocol;
pub use self::tascam_protocol::TascamProtocolExt;
pub use self::tascam_protocol::{TascamProtocol, NONE_TASCAM_PROTOCOL};

mod snd_motu_register_dsp_parameter;
pub use self::snd_motu_register_dsp_parameter::SndMotuRegisterDspParameter;

mod enums;
pub use self::enums::AlsaFirewireError;
pub use self::enums::AlsaFirewireType;
pub use self::enums::EfwProtocolError;

#[doc(hidden)]
pub mod traits {
    pub use super::AlsaFirewireExt;
    pub use super::EfwProtocolExt;
    pub use super::MotuCommandDspExt;
    pub use super::MotuRegisterDspExt;
    pub use super::QuadletNotificationExt;
    pub use super::TascamProtocolExt;
}
