// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use hitaki_sys;
use std::fmt;

glib_wrapper! {
    pub struct MotuCommandDsp(Interface<hitaki_sys::HitakiMotuCommandDsp>);

    match fn {
        get_type => || hitaki_sys::hitaki_motu_command_dsp_get_type(),
    }
}

pub const NONE_MOTU_COMMAND_DSP: Option<&MotuCommandDsp> = None;

pub trait MotuCommandDspExt: 'static {
    //fn read_float_meter(&self, meter: /*Unimplemented*/FixedArray TypeId { ns_id: 0, id: 20 }; 400) -> Result<(), glib::Error>;
}

impl<O: IsA<MotuCommandDsp>> MotuCommandDspExt for O {
    //fn read_float_meter(&self, meter: /*Unimplemented*/FixedArray TypeId { ns_id: 0, id: 20 }; 400) -> Result<(), glib::Error> {
    //    unsafe { TODO: call hitaki_sys:hitaki_motu_command_dsp_read_float_meter() }
    //}
}

impl fmt::Display for MotuCommandDsp {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "MotuCommandDsp")
    }
}
