// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use hitaki_sys;
use std::fmt;
use AlsaFirewire;
use QuadletNotification;

glib_wrapper! {
    pub struct SndDigi00x(Object<hitaki_sys::HitakiSndDigi00x, hitaki_sys::HitakiSndDigi00xClass, SndDigi00xClass>) @implements AlsaFirewire, QuadletNotification;

    match fn {
        get_type => || hitaki_sys::hitaki_snd_digi00x_get_type(),
    }
}

impl SndDigi00x {
    pub fn new() -> SndDigi00x {
        unsafe { from_glib_full(hitaki_sys::hitaki_snd_digi00x_new()) }
    }
}

impl Default for SndDigi00x {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_SND_DIGI00X: Option<&SndDigi00x> = None;

impl fmt::Display for SndDigi00x {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "SndDigi00x")
    }
}
