// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::AlsaFirewire;
use crate::MotuCommandDsp;
use crate::MotuRegisterDsp;
use crate::QuadletNotification;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "HitakiSndMotu")]
    pub struct SndMotu(Object<ffi::HitakiSndMotu, ffi::HitakiSndMotuClass>) @implements AlsaFirewire, MotuCommandDsp, MotuRegisterDsp, QuadletNotification;

    match fn {
        type_ => || ffi::hitaki_snd_motu_get_type(),
    }
}

impl SndMotu {
    pub const NONE: Option<&'static SndMotu> = None;

    #[doc(alias = "hitaki_snd_motu_new")]
    pub fn new() -> SndMotu {
        unsafe { from_glib_full(ffi::hitaki_snd_motu_new()) }
    }
}

impl Default for SndMotu {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SndMotu {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("SndMotu")
    }
}
