// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use hitaki_sys;
use std::fmt;
use AlsaFirewire;
use MotuCommandDsp;
use MotuRegisterDsp;
use QuadletNotification;

glib_wrapper! {
    pub struct SndMotu(Object<hitaki_sys::HitakiSndMotu, hitaki_sys::HitakiSndMotuClass, SndMotuClass>) @implements AlsaFirewire, MotuCommandDsp, MotuRegisterDsp, QuadletNotification;

    match fn {
        get_type => || hitaki_sys::hitaki_snd_motu_get_type(),
    }
}

impl SndMotu {
    pub fn new() -> SndMotu {
        unsafe { from_glib_full(hitaki_sys::hitaki_snd_motu_new()) }
    }
}

impl Default for SndMotu {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_SND_MOTU: Option<&SndMotu> = None;

impl fmt::Display for SndMotu {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "SndMotu")
    }
}
