// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use hitaki_sys;
use std::fmt;
use AlsaFirewire;

glib_wrapper! {
    pub struct SndUnit(Object<hitaki_sys::HitakiSndUnit, hitaki_sys::HitakiSndUnitClass, SndUnitClass>) @implements AlsaFirewire;

    match fn {
        get_type => || hitaki_sys::hitaki_snd_unit_get_type(),
    }
}

impl SndUnit {
    pub fn new() -> SndUnit {
        unsafe { from_glib_full(hitaki_sys::hitaki_snd_unit_new()) }
    }
}

impl Default for SndUnit {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_SND_UNIT: Option<&SndUnit> = None;

impl fmt::Display for SndUnit {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "SndUnit")
    }
}
