// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::AlsaFirewire;
use crate::EfwProtocol;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "HitakiSndEfw")]
    pub struct SndEfw(Object<ffi::HitakiSndEfw, ffi::HitakiSndEfwClass>) @implements AlsaFirewire, EfwProtocol;

    match fn {
        type_ => || ffi::hitaki_snd_efw_get_type(),
    }
}

impl SndEfw {
    pub const NONE: Option<&'static SndEfw> = None;

    #[doc(alias = "hitaki_snd_efw_new")]
    pub fn new() -> SndEfw {
        unsafe { from_glib_full(ffi::hitaki_snd_efw_new()) }
    }
}

impl Default for SndEfw {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SndEfw {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("SndEfw")
    }
}
