// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{AlsaFirewire, QuadletNotification};
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    /// A GObject-derived object for sound unit of TCAT DICE ASICs.
    ///
    /// The [`SndDice`][crate::SndDice] is object class derived from `GObject::Object` for sound unit of TCAT
    /// DICE ASICs supported by ALSA dice driver (`snd-dice`).
    ///
    /// # Implements
    ///
    /// [`AlsaFirewireExt`][trait@crate::prelude::AlsaFirewireExt], [`QuadletNotificationExt`][trait@crate::prelude::QuadletNotificationExt]
    #[doc(alias = "HitakiSndDice")]
    pub struct SndDice(Object<ffi::HitakiSndDice, ffi::HitakiSndDiceClass>) @implements AlsaFirewire, QuadletNotification;

    match fn {
        type_ => || ffi::hitaki_snd_dice_get_type(),
    }
}

impl SndDice {
    pub const NONE: Option<&'static SndDice> = None;

    /// Instantiate [`SndDice`][crate::SndDice] object and return the instance.
    ///
    /// # Returns
    ///
    /// an instance of [`SndDice`][crate::SndDice].
    #[doc(alias = "hitaki_snd_dice_new")]
    pub fn new() -> SndDice {
        unsafe { from_glib_full(ffi::hitaki_snd_dice_new()) }
    }
}

impl Default for SndDice {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SndDice {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("SndDice")
    }
}
