// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use hitaki_sys;
use std::fmt;
use AlsaFirewire;
use TascamProtocol;

glib_wrapper! {
    pub struct SndTascam(Object<hitaki_sys::HitakiSndTascam, hitaki_sys::HitakiSndTascamClass, SndTascamClass>) @implements AlsaFirewire, TascamProtocol;

    match fn {
        get_type => || hitaki_sys::hitaki_snd_tascam_get_type(),
    }
}

impl SndTascam {
    pub fn new() -> SndTascam {
        unsafe { from_glib_full(hitaki_sys::hitaki_snd_tascam_new()) }
    }
}

impl Default for SndTascam {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_SND_TASCAM: Option<&SndTascam> = None;

impl fmt::Display for SndTascam {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "SndTascam")
    }
}
