// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{AlsaFirewire, EfwProtocol};
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    /// A GObject-derived object for sound unit of Echo Audio Fireworks.
    ///
    /// The [`SndEfw`][crate::SndEfw] is an object class derived from `GObject::Object` with protocol
    /// implementation for Echo Audio Fireworks devices supported by ALSA fireworks driver
    /// (`snd-fireworks`).
    ///
    /// # Implements
    ///
    /// [`AlsaFirewireExt`][trait@crate::prelude::AlsaFirewireExt], [`EfwProtocolExt`][trait@crate::prelude::EfwProtocolExt], [`EfwProtocolExtManual`][trait@crate::prelude::EfwProtocolExtManual]
    #[doc(alias = "HitakiSndEfw")]
    pub struct SndEfw(Object<ffi::HitakiSndEfw, ffi::HitakiSndEfwClass>) @implements AlsaFirewire, EfwProtocol;

    match fn {
        type_ => || ffi::hitaki_snd_efw_get_type(),
    }
}

impl SndEfw {
    pub const NONE: Option<&'static SndEfw> = None;

    /// Instantiate [`SndEfw`][crate::SndEfw] object and return it.
    ///
    /// # Returns
    ///
    /// an instance of [`SndEfw`][crate::SndEfw].
    #[doc(alias = "hitaki_snd_efw_new")]
    pub fn new() -> SndEfw {
        unsafe { from_glib_full(ffi::hitaki_snd_efw_new()) }
    }
}

impl Default for SndEfw {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SndEfw {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("SndEfw")
    }
}
