// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib;
use glib::object::Cast;
use glib::object::IsA;
use glib::object::ObjectExt;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib_sys;
use gobject_sys;
use hitaki_sys;
use libc;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib_wrapper! {
    pub struct TascamProtocol(Interface<hitaki_sys::HitakiTascamProtocol>);

    match fn {
        get_type => || hitaki_sys::hitaki_tascam_protocol_get_type(),
    }
}

pub const NONE_TASCAM_PROTOCOL: Option<&TascamProtocol> = None;

pub trait TascamProtocolExt: 'static {
    fn connect_changed<F: Fn(&Self, u32, u32, u32) + 'static>(&self, f: F) -> SignalHandlerId;

    fn emit_changed(&self, index: u32, before: u32, after: u32);
}

impl<O: IsA<TascamProtocol>> TascamProtocolExt for O {
    fn connect_changed<F: Fn(&Self, u32, u32, u32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn changed_trampoline<P, F: Fn(&P, u32, u32, u32) + 'static>(
            this: *mut hitaki_sys::HitakiTascamProtocol,
            index: libc::c_uint,
            before: libc::c_uint,
            after: libc::c_uint,
            f: glib_sys::gpointer,
        ) where
            P: IsA<TascamProtocol>,
        {
            let f: &F = &*(f as *const F);
            f(
                &TascamProtocol::from_glib_borrow(this).unsafe_cast_ref(),
                index,
                before,
                after,
            )
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"changed\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    changed_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn emit_changed(&self, index: u32, before: u32, after: u32) {
        let _ = unsafe {
            glib::Object::from_glib_borrow(self.as_ptr() as *mut gobject_sys::GObject)
                .emit("changed", &[&index, &before, &after])
                .unwrap()
        };
    }
}

impl fmt::Display for TascamProtocol {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "TascamProtocol")
    }
}
