// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use hitaki_sys::*;
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::mem::{align_of, size_of};
use std::path::Path;
use std::process::Command;
use std::str;
use tempfile::Builder;

static PACKAGES: &[&str] = &["hitaki"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {:?} failed, {}", &cmd, status).into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{} {}", name, err).into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG").unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    let out = cmd.output()?;
    if !out.status.success() {
        return Err(format!("command {:?} returned {}", &cmd, out.status).into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
#[cfg(target_os = "linux")]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let mut words = l.trim().split(';');
        let name = words.next().expect("Failed to parse name").to_owned();
        let value = words
            .next()
            .and_then(|s| s.parse().ok())
            .expect("Failed to parse value");
        c_constants.push((name, value));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {:?}\nC:    {:?}", rust_name, c_name,);
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {}\nRust: {:?}\nC:    {:?}",
                rust_name, rust_value, &c_value
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
#[cfg(target_os = "linux")]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let mut words = l.trim().split(';');
        let name = words.next().expect("Failed to parse name").to_owned();
        let size = words
            .next()
            .and_then(|s| s.parse().ok())
            .expect("Failed to parse size");
        let alignment = words
            .next()
            .and_then(|s| s.parse().ok())
            .expect("Failed to parse alignment");
        c_layouts.push((name, Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {:?}\nC:    {:?}", rust_name, c_name,);
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!(
                "Layout mismatch for {}\nRust: {:?}\nC:    {:?}",
                rust_name, rust_layout, &c_layout
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut abi_cmd = Command::new(exe);
    let output = abi_cmd.output()?;
    if !output.status.success() {
        return Err(format!("command {:?} failed, {:?}", &abi_cmd, &output).into());
    }

    Ok(String::from_utf8(output.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    (
        "HitakiAlsaFirewireError",
        Layout {
            size: size_of::<HitakiAlsaFirewireError>(),
            alignment: align_of::<HitakiAlsaFirewireError>(),
        },
    ),
    (
        "HitakiAlsaFirewireInterface",
        Layout {
            size: size_of::<HitakiAlsaFirewireInterface>(),
            alignment: align_of::<HitakiAlsaFirewireInterface>(),
        },
    ),
    (
        "HitakiAlsaFirewireType",
        Layout {
            size: size_of::<HitakiAlsaFirewireType>(),
            alignment: align_of::<HitakiAlsaFirewireType>(),
        },
    ),
    (
        "HitakiEfwProtocolError",
        Layout {
            size: size_of::<HitakiEfwProtocolError>(),
            alignment: align_of::<HitakiEfwProtocolError>(),
        },
    ),
    (
        "HitakiEfwProtocolInterface",
        Layout {
            size: size_of::<HitakiEfwProtocolInterface>(),
            alignment: align_of::<HitakiEfwProtocolInterface>(),
        },
    ),
    (
        "HitakiMotuCommandDspInterface",
        Layout {
            size: size_of::<HitakiMotuCommandDspInterface>(),
            alignment: align_of::<HitakiMotuCommandDspInterface>(),
        },
    ),
    (
        "HitakiMotuRegisterDspInterface",
        Layout {
            size: size_of::<HitakiMotuRegisterDspInterface>(),
            alignment: align_of::<HitakiMotuRegisterDspInterface>(),
        },
    ),
    (
        "HitakiQuadletNotificationInterface",
        Layout {
            size: size_of::<HitakiQuadletNotificationInterface>(),
            alignment: align_of::<HitakiQuadletNotificationInterface>(),
        },
    ),
    (
        "HitakiSndDice",
        Layout {
            size: size_of::<HitakiSndDice>(),
            alignment: align_of::<HitakiSndDice>(),
        },
    ),
    (
        "HitakiSndDiceClass",
        Layout {
            size: size_of::<HitakiSndDiceClass>(),
            alignment: align_of::<HitakiSndDiceClass>(),
        },
    ),
    (
        "HitakiSndDigi00x",
        Layout {
            size: size_of::<HitakiSndDigi00x>(),
            alignment: align_of::<HitakiSndDigi00x>(),
        },
    ),
    (
        "HitakiSndDigi00xClass",
        Layout {
            size: size_of::<HitakiSndDigi00xClass>(),
            alignment: align_of::<HitakiSndDigi00xClass>(),
        },
    ),
    (
        "HitakiSndEfw",
        Layout {
            size: size_of::<HitakiSndEfw>(),
            alignment: align_of::<HitakiSndEfw>(),
        },
    ),
    (
        "HitakiSndEfwClass",
        Layout {
            size: size_of::<HitakiSndEfwClass>(),
            alignment: align_of::<HitakiSndEfwClass>(),
        },
    ),
    (
        "HitakiSndFireface",
        Layout {
            size: size_of::<HitakiSndFireface>(),
            alignment: align_of::<HitakiSndFireface>(),
        },
    ),
    (
        "HitakiSndFirefaceClass",
        Layout {
            size: size_of::<HitakiSndFirefaceClass>(),
            alignment: align_of::<HitakiSndFirefaceClass>(),
        },
    ),
    (
        "HitakiSndMotu",
        Layout {
            size: size_of::<HitakiSndMotu>(),
            alignment: align_of::<HitakiSndMotu>(),
        },
    ),
    (
        "HitakiSndMotuClass",
        Layout {
            size: size_of::<HitakiSndMotuClass>(),
            alignment: align_of::<HitakiSndMotuClass>(),
        },
    ),
    (
        "HitakiSndMotuRegisterDspParameter",
        Layout {
            size: size_of::<HitakiSndMotuRegisterDspParameter>(),
            alignment: align_of::<HitakiSndMotuRegisterDspParameter>(),
        },
    ),
    (
        "HitakiSndTascam",
        Layout {
            size: size_of::<HitakiSndTascam>(),
            alignment: align_of::<HitakiSndTascam>(),
        },
    ),
    (
        "HitakiSndTascamClass",
        Layout {
            size: size_of::<HitakiSndTascamClass>(),
            alignment: align_of::<HitakiSndTascamClass>(),
        },
    ),
    (
        "HitakiSndUnit",
        Layout {
            size: size_of::<HitakiSndUnit>(),
            alignment: align_of::<HitakiSndUnit>(),
        },
    ),
    (
        "HitakiSndUnitClass",
        Layout {
            size: size_of::<HitakiSndUnitClass>(),
            alignment: align_of::<HitakiSndUnitClass>(),
        },
    ),
    (
        "HitakiTascamProtocolInterface",
        Layout {
            size: size_of::<HitakiTascamProtocolInterface>(),
            alignment: align_of::<HitakiTascamProtocolInterface>(),
        },
    ),
    (
        "HitakiTimestampedQuadletNotificationInterface",
        Layout {
            size: size_of::<HitakiTimestampedQuadletNotificationInterface>(),
            alignment: align_of::<HitakiTimestampedQuadletNotificationInterface>(),
        },
    ),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_FAILED", "0"),
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_IS_DISCONNECTED", "6"),
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_IS_LOCKED", "4"),
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_IS_NOT_OPENED", "2"),
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_IS_OPENED", "1"),
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_IS_UNLOCKED", "5"),
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_IS_USED", "3"),
    ("(gint) HITAKI_ALSA_FIREWIRE_ERROR_WRONG_CLASS", "7"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_BEBOB", "3"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_DICE", "1"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_DIGI00X", "5"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_FIREFACE", "8"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_FIREWORKS", "2"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_MOTU", "7"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_OXFW", "4"),
    ("(gint) HITAKI_ALSA_FIREWIRE_TYPE_TASCAM", "6"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD", "1"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_CHANNEL", "10"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_CLOCK", "9"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_COMMAND", "2"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_LED", "14"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_MIRROR", "13"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_PAN", "11"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_PARAMETER", "15"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_QUAD_COUNT", "4"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_BAD_RATE", "8"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_COMM_ERR", "3"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_DSP_TIMEOUT", "7"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_FLASH_BUSY", "12"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_INCOMPLETE", "-2147483648"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_INVALID", "-1"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_OK", "0"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_TIMEOUT", "6"),
    ("(gint) HITAKI_EFW_PROTOCOL_ERROR_UNSUPPORTED", "5"),
];
