// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "HitakiAlsaFirewireError", sizeof(HitakiAlsaFirewireError), alignof(HitakiAlsaFirewireError));
    printf("%s;%zu;%zu\n", "HitakiAlsaFirewireInterface", sizeof(HitakiAlsaFirewireInterface), alignof(HitakiAlsaFirewireInterface));
    printf("%s;%zu;%zu\n", "HitakiAlsaFirewireType", sizeof(HitakiAlsaFirewireType), alignof(HitakiAlsaFirewireType));
    printf("%s;%zu;%zu\n", "HitakiEfwProtocolError", sizeof(HitakiEfwProtocolError), alignof(HitakiEfwProtocolError));
    printf("%s;%zu;%zu\n", "HitakiEfwProtocolInterface", sizeof(HitakiEfwProtocolInterface), alignof(HitakiEfwProtocolInterface));
    printf("%s;%zu;%zu\n", "HitakiMotuCommandDspInterface", sizeof(HitakiMotuCommandDspInterface), alignof(HitakiMotuCommandDspInterface));
    printf("%s;%zu;%zu\n", "HitakiMotuRegisterDspInterface", sizeof(HitakiMotuRegisterDspInterface), alignof(HitakiMotuRegisterDspInterface));
    printf("%s;%zu;%zu\n", "HitakiQuadletNotificationInterface", sizeof(HitakiQuadletNotificationInterface), alignof(HitakiQuadletNotificationInterface));
    printf("%s;%zu;%zu\n", "HitakiSndDice", sizeof(HitakiSndDice), alignof(HitakiSndDice));
    printf("%s;%zu;%zu\n", "HitakiSndDiceClass", sizeof(HitakiSndDiceClass), alignof(HitakiSndDiceClass));
    printf("%s;%zu;%zu\n", "HitakiSndDigi00x", sizeof(HitakiSndDigi00x), alignof(HitakiSndDigi00x));
    printf("%s;%zu;%zu\n", "HitakiSndDigi00xClass", sizeof(HitakiSndDigi00xClass), alignof(HitakiSndDigi00xClass));
    printf("%s;%zu;%zu\n", "HitakiSndEfw", sizeof(HitakiSndEfw), alignof(HitakiSndEfw));
    printf("%s;%zu;%zu\n", "HitakiSndEfwClass", sizeof(HitakiSndEfwClass), alignof(HitakiSndEfwClass));
    printf("%s;%zu;%zu\n", "HitakiSndFireface", sizeof(HitakiSndFireface), alignof(HitakiSndFireface));
    printf("%s;%zu;%zu\n", "HitakiSndFirefaceClass", sizeof(HitakiSndFirefaceClass), alignof(HitakiSndFirefaceClass));
    printf("%s;%zu;%zu\n", "HitakiSndMotu", sizeof(HitakiSndMotu), alignof(HitakiSndMotu));
    printf("%s;%zu;%zu\n", "HitakiSndMotuClass", sizeof(HitakiSndMotuClass), alignof(HitakiSndMotuClass));
    printf("%s;%zu;%zu\n", "HitakiSndMotuRegisterDspParameter", sizeof(HitakiSndMotuRegisterDspParameter), alignof(HitakiSndMotuRegisterDspParameter));
    printf("%s;%zu;%zu\n", "HitakiSndTascam", sizeof(HitakiSndTascam), alignof(HitakiSndTascam));
    printf("%s;%zu;%zu\n", "HitakiSndTascamClass", sizeof(HitakiSndTascamClass), alignof(HitakiSndTascamClass));
    printf("%s;%zu;%zu\n", "HitakiSndUnit", sizeof(HitakiSndUnit), alignof(HitakiSndUnit));
    printf("%s;%zu;%zu\n", "HitakiSndUnitClass", sizeof(HitakiSndUnitClass), alignof(HitakiSndUnitClass));
    printf("%s;%zu;%zu\n", "HitakiTascamProtocolInterface", sizeof(HitakiTascamProtocolInterface), alignof(HitakiTascamProtocolInterface));
    printf("%s;%zu;%zu\n", "HitakiTimestampedQuadletNotificationInterface", sizeof(HitakiTimestampedQuadletNotificationInterface), alignof(HitakiTimestampedQuadletNotificationInterface));
    return 0;
}
