[package]
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
description = "API bindings for libhitaki library"
license = "MIT"
name = "hitaki"
repository = "https://github.com/alsa-project/hitaki-rs/"
version = "0.1.0"

[lib]
name = "hitaki"

[dependencies]
libc = "0.2"
glib = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"

hitaki-sys = { path = "../hitaki-sys", version = "0.1" }

[dev-dependencies]
gir-format-check = "^0.1"
